apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-connection-string-external
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: kv-secret-store
    kind: SecretStore

  target:
    name: db-connection-string-secret
    creationPolicy: Owner

  data:
  - secretKey: ConnectionStrings__CoreDB
    remoteRef:
      key: sql-connection-string
