apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sql-connection             # MUST match your deployment
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aks-eso-kv
    kind: ClusterSecretStore

  target:
    name: sql-connection           # MUST match your deployment
    creationPolicy: Owner

  data:
    - secretKey: connectionString  # Key the app expects
      remoteRef:
        key: sql-connection-string # The key in Key Vault

