apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sql-connection-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aks-eso-kv
    kind: ClusterSecretStore

  target:
    name: sql-connection
    creationPolicy: Owner

  data:
    - secretKey: connectionString
      remoteRef:
        key: sql-connection-string
