apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-connection-string
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target:
    name: db-connection-string-secret
    creationPolicy: Owner
  data:
  - secretKey: ConnectionStrings__CoreDB
    remoteRef:
      key: db-connection-string-in-keyvault
