apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault-store
  namespace: default
spec:
  provider:
    azurekv:
      tenantId: "<AZURE_TENANT_ID>"
      vaultUrl: "https://<KEYVAULT_NAME>.vault.azure.net/"
      authType: WorkloadIdentity
      serviceAccountRef:
        name: dotnet-sa
