apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aks-eso-kv
spec:
  provider:
    azurekv:
      vaultUrl: "https://kv-m5ko.vault.azure.net"
      tenantId: "5bb2f52d-f721-43ad-a5a7-e7804488c107"

      authType: WorkloadIdentity

      serviceAccountRef:
        name: dotnet-sa
        namespace: default

      identityId: "007fc5da-8aa5-489b-ad98-a2363f37993a"
