apiVersion: v1
kind: ServiceAccount
metadata:
  name: dotnet-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "007fc5da-8aa5-489b-ad98-a2363f37993a"
  labels:
    azure.workload.identity/use: "true"
