apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  annotations:
    azure.workload.identity/client-id: "99e512b4-fd3e-4a37-9952-ff685c26b6b3"
  labels:
    azure.workload.identity/use: "true"
